In [1]:
import pandas as pd

In [2]:
oo=pd.read_csv('/Users/dibyajyoti.nayak/Documents/Technical_Stuff/Pandas/data_set/SummerOlympic.csv',skiprows=4)

Index

In [4]:
type(oo.index)

pandas.core.indexes.range.RangeIndex

In [7]:
oo.head()

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver

In [11]:
oo.index[1]

1

In [12]:
oo.index[1]=2

TypeError: Index does not support mutable operations

TypeError: Index does not support mutable operations ----> Index doesnt support mutable operations. They are immutable. By default the 1st column of the xls sheet has indexing. We can specify on which column the dataframe has indexing on

set_index

In [18]:
oo.head()

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver

In [19]:
oo.set_index('Athlete')

,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
Athlete,,,,,,,,,
"HAJOS, Alfred",Athens,1896,Aquatics,Swimming,HUN,Men,100m freestyle,M,Gold
"HERSCHMANN, Otto",Athens,1896,Aquatics,Swimming,AUT,Men,100m freestyle,M,Silver
"DRIVAS, Dimitrios",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Bronze
"MALOKINIS, Ioannis",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Gold
"CHASAPIS, Spiridon",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Silver
"CHOROPHAS, Efstathios",Athens,1896,Aquatics,Swimming,GRE,Men,1200m freestyle,M,Bronze
"HAJOS, Alfred",Athens,1896,Aquatics,Swimming,HUN,Men,1200m freestyle,M,Gold
"ANDREOU, Joannis",Athens,1896,Aquatics,Swimming,GRE,Men,1200m freestyle,M,Silver
"CHOROPHAS, Efstathios",Athens,1896,Aquatics,Swimming,GRE,Men,400m freestyle,M,Bronze
"NEUMANN, Paul",Athens,1896,Aquatics,Swimming,AUT,Men,400m freestyle,M,Gold
"PEPANOS, Antonios",Athens,1896,Aquatics,Swimming,GRE,Men,400m freestyle,M,Silver
"LANE, Francis",Athens,1896,Athletics,Athletics,USA,Men,100m,M,Bronze
"SZOKOLYI, Alajos",Athens,1896,Athletics,Athletics,HUN,Men,100m,M,Bronze
"BURKE, Thomas",Athens,1896,Athletics,Athletics,USA,Men,100m,M,Gold
"HOFMANN, Fritz",Athens,1896,Athletics,Athletics,GER,Men,100m,M,Silver
"CURTIS, Thomas",Athens,1896,Athletics,Athletics,USA,Men,110m hurdles,M,Gold
"GOULDING, Grantley",Athens,1896,Athletics,Athletics,GBR,Men,110m hurdles,M,Silver
"LERMUSIAUX, Albin",Athens,1896,Athletics,Athletics,FRA,Men,1500m,M,Bronze
"FLACK, Edwin",Athens,1896,Athletics,Athletics,AUS,Men,1500m,M,Gold
"BLAKE, Arthur",Athens,1896,Athletics,Athletics,USA,Men,1500m,M,Silver
"GMELIN, Charles",Athens,1896,Athletics,Athletics,GBR,Men,400m,M,Bronze
"BURKE, Thomas",Athens,1896,Athletics,Athletics,USA,Men,400m,M,Gold
"JAMISON, Herbert",Athens,1896,Athletics,Athletics,USA,Men,400m,M,Silver
"GOLEMIS, Dimitrios",Athens,1896,Athletics,Athletics,GRE,Men,800m,M,Bronze
"FLACK, Edwin",Athens,1896,Athletics,Athletics,AUS,Men,800m,M,Gold
"DANI, Nandor",Athens,1896,Athletics,Athletics,HUN,Men,800m,M,Silver
"VERSIS, Sotirios",Athens,1896,Athletics,Athletics,GRE,Men,discus throw,M,Bronze
"GARRETT, Robert",Athens,1896,Athletics,Athletics,USA,Men,discus throw,M,Gold
"PARASKEVOPOULOS, Panagiotis",Athens,1896,Athletics,Athletics,GRE,Men,discus throw,M,Silver
"CLARK, Ellery",Athens,1896,Athletics,Athletics,USA,Men,high jump,M,Gold
...,...,...,...,...,...,...,...,...,...
"MUTALIMOV, Marid",Beijing,2008,Wrestling,Wrestling Free.,KAZ,Men,96 - 120kg,M,Bronze
"TAYMAZOV, Artur",Beijing,2008,Wrestling,Wrestling Free.,UZB,Men,96 - 120kg,M,Gold
"AKHMEDOV, Bakhtiyar",Beijing,2008,Wrestling,Wrestling Free.,RUS,Men,96 - 120kg,M,Silver
"AMOYAN, Roman",Beijing,2008,Wrestling,Wrestling Gre-R,ARM,Men,- 55kg,M,Bronze
"PARK, Eun-Chul",Beijing,2008,Wrestling,Wrestling Gre-R,KOR,Men,- 55kg,M,Bronze
"MANKIEV, Nazyr",Beijing,2008,Wrestling,Wrestling Gre-R,RUS,Men,- 55kg,M,Gold
"BAYRAMOV, Rovshan",Beijing,2008,Wrestling,Wrestling Gre-R,AZE,Men,- 55kg,M,Silver
"TENGIZBAYEV, Nurbakyt",Beijing,2008,Wrestling,Wrestling Gre-R,KAZ,Men,55 - 60kg,M,Bronze
"TIUMENBAEV, Ruslan",Beijing,2008,Wrestling,Wrestling Gre-R,KGZ,Men,55 - 60kg,M,Bronze
"ALBIEV, Islam-Beka",Beijing,2008,Wrestling,Wrestling Gre-R,RUS,Men,55 - 60kg,M,Gold
"RAHIMOV, Vitaliy",Beijing,2008,Wrestling,Wrestling Gre-R,AZE,Men,55 - 60kg,M,Silver
"SIAMIONAU, Mikhail",Beijing,2008,Wrestling,Wrestling Gre-R,BLR,Men,60 - 66kg,M,Bronze
"VARDANYAN, Armen",Beijing,2008,Wrestling,Wrestling Gre-R,UKR,Men,60 - 66kg,M,Bronze
"GUENOT, Steeve",Beijing,2008,Wrestling,Wrestling Gre-R,FRA,Men,60 - 66kg,M,Gold
"BEGALIEV, Kanatbek",Beijing,2008,Wrestling,Wrestling Gre-R,KGZ,Men,60 - 66kg,M,Silver
"GUENOT, Christophe",Beijing,2008,Wrestling,Wrestling Gre-R,FRA,Men,66 - 74kg,M,Bronze
"YANAKIEV, Yavor",Beijing,2008,Wrestling,Wrestling Gre-R,BUL,Men,66 - 74kg,M,Bronze
"KVIRKELIA, Manuchar",Beijing,2008,Wrestling,Wrestling Gre-R,GEO,Men,66 - 74kg,M,Gold
"CHANG, Yongxiang",Beijing,2008,Wrestling,Wrestling Gre-R,CHN,Men,66 - 74kg,M,Silver
"AVLUCA, Nazmi",Beijing,2008,Wrestling,Wrestling Gre-R,TUR,Men,74 - 84kg,M,Bronze
"MINGUZZI, Andrea",Beijing,2008,Wrestling,Wrestling Gre-R,ITA,Men,74 - 84kg,M,Gold
"FODOR, Zoltan",Beijing,2008,Wrestling,Wrestling Gre-R,HUN,Men,74 - 84kg,M,Silver
"MAMBETOV, Asset",Beijing,2008,Wrestling,Wrestling Gre-R,KAZ,Men,84 - 96kg,M,Bronze
"WHEELER, Adam",Beijing,2008,Wrestling,Wrestling Gre-R,USA,Men,84 - 96kg,M,Bronze
"KHUSHTOV, Aslanbek",Beijing,2008,Wrestling,Wrestling Gre-R,RUS,Men,84 - 96kg,M,Gold
"ENGLICH, Mirko",Beijing,2008,Wrestling,Wrestling Gre-R,GER,Men,84 - 96kg,M,Silver
"MIZGAITIS, Mindaugas",Beijing,2008,Wrestling,Wrestling Gre-R,LTU,Men,96 - 120kg,M,Bronze
"PATRIKEEV, Yuri",Beijing,2008,Wrestling,Wrestling Gre-R,ARM,Men,96 - 120kg,M,Bronze
"LOPEZ, Mijain",Beijing,2008,Wrestling,Wrestling Gre-R,CUB,Men,96 - 120kg,M,Gold
"BAROEV, Khasan",Beijing,2008,Wrestling,Wrestling Gre-R,RUS,Men,96 - 120kg,M,Silver

In [20]:
oo.head()

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver

We can see from above output that indexing has been reversed. So in order to commit our changed index we have to use 'inplace=True'

In [21]:
oo.set_index('Athlete',inplace=True)

In [23]:
oo.head()

,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
Athlete,,,,,,,,,
"HAJOS, Alfred",Athens,1896,Aquatics,Swimming,HUN,Men,100m freestyle,M,Gold
"HERSCHMANN, Otto",Athens,1896,Aquatics,Swimming,AUT,Men,100m freestyle,M,Silver
"DRIVAS, Dimitrios",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Bronze
"MALOKINIS, Ioannis",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Gold
"CHASAPIS, Spiridon",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Silver

In [24]:
oo.index[1]

'HERSCHMANN, Otto'

reset_index

In [26]:
oo.reset_index(inplace=True)

In [27]:
oo

,Athlete,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
0,"HAJOS, Alfred",Athens,1896,Aquatics,Swimming,HUN,Men,100m freestyle,M,Gold
1,"HERSCHMANN, Otto",Athens,1896,Aquatics,Swimming,AUT,Men,100m freestyle,M,Silver
2,"DRIVAS, Dimitrios",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Bronze
3,"MALOKINIS, Ioannis",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Gold
4,"CHASAPIS, Spiridon",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Silver
5,"CHOROPHAS, Efstathios",Athens,1896,Aquatics,Swimming,GRE,Men,1200m freestyle,M,Bronze
6,"HAJOS, Alfred",Athens,1896,Aquatics,Swimming,HUN,Men,1200m freestyle,M,Gold
7,"ANDREOU, Joannis",Athens,1896,Aquatics,Swimming,GRE,Men,1200m freestyle,M,Silver
8,"CHOROPHAS, Efstathios",Athens,1896,Aquatics,Swimming,GRE,Men,400m freestyle,M,Bronze
9,"NEUMANN, Paul",Athens,1896,Aquatics,Swimming,AUT,Men,400m freestyle,M,Gold
10,"PEPANOS, Antonios",Athens,1896,Aquatics,Swimming,GRE,Men,400m freestyle,M,Silver
11,"LANE, Francis",Athens,1896,Athletics,Athletics,USA,Men,100m,M,Bronze
12,"SZOKOLYI, Alajos",Athens,1896,Athletics,Athletics,HUN,Men,100m,M,Bronze
13,"BURKE, Thomas",Athens,1896,Athletics,Athletics,USA,Men,100m,M,Gold
14,"HOFMANN, Fritz",Athens,1896,Athletics,Athletics,GER,Men,100m,M,Silver
15,"CURTIS, Thomas",Athens,1896,Athletics,Athletics,USA,Men,110m hurdles,M,Gold
16,"GOULDING, Grantley",Athens,1896,Athletics,Athletics,GBR,Men,110m hurdles,M,Silver
17,"LERMUSIAUX, Albin",Athens,1896,Athletics,Athletics,FRA,Men,1500m,M,Bronze
18,"FLACK, Edwin",Athens,1896,Athletics,Athletics,AUS,Men,1500m,M,Gold
19,"BLAKE, Arthur",Athens,1896,Athletics,Athletics,USA,Men,1500m,M,Silver
20,"GMELIN, Charles",Athens,1896,Athletics,Athletics,GBR,Men,400m,M,Bronze
21,"BURKE, Thomas",Athens,1896,Athletics,Athletics,USA,Men,400m,M,Gold
22,"JAMISON, Herbert",Athens,1896,Athletics,Athletics,USA,Men,400m,M,Silver
23,"GOLEMIS, Dimitrios",Athens,1896,Athletics,Athletics,GRE,Men,800m,M,Bronze
24,"FLACK, Edwin",Athens,1896,Athletics,Athletics,AUS,Men,800m,M,Gold
25,"DANI, Nandor",Athens,1896,Athletics,Athletics,HUN,Men,800m,M,Silver
26,"VERSIS, Sotirios",Athens,1896,Athletics,Athletics,GRE,Men,discus throw,M,Bronze
27,"GARRETT, Robert",Athens,1896,Athletics,Athletics,USA,Men,discus throw,M,Gold
28,"PARASKEVOPOULOS, Panagiotis",Athens,1896,Athletics,Athletics,GRE,Men,discus throw,M,Silver
29,"CLARK, Ellery",Athens,1896,Athletics,Athletics,USA,Men,high jump,M,Gold
...,...,...,...,...,...,...,...,...,...,...
29186,"MUTALIMOV, Marid",Beijing,2008,Wrestling,Wrestling Free.,KAZ,Men,96 - 120kg,M,Bronze
29187,"TAYMAZOV, Artur",Beijing,2008,Wrestling,Wrestling Free.,UZB,Men,96 - 120kg,M,Gold
29188,"AKHMEDOV, Bakhtiyar",Beijing,2008,Wrestling,Wrestling Free.,RUS,Men,96 - 120kg,M,Silver
29189,"AMOYAN, Roman",Beijing,2008,Wrestling,Wrestling Gre-R,ARM,Men,- 55kg,M,Bronze
29190,"PARK, Eun-Chul",Beijing,2008,Wrestling,Wrestling Gre-R,KOR,Men,- 55kg,M,Bronze
29191,"MANKIEV, Nazyr",Beijing,2008,Wrestling,Wrestling Gre-R,RUS,Men,- 55kg,M,Gold
29192,"BAYRAMOV, Rovshan",Beijing,2008,Wrestling,Wrestling Gre-R,AZE,Men,- 55kg,M,Silver
29193,"TENGIZBAYEV, Nurbakyt",Beijing,2008,Wrestling,Wrestling Gre-R,KAZ,Men,55 - 60kg,M,Bronze
29194,"TIUMENBAEV, Ruslan",Beijing,2008,Wrestling,Wrestling Gre-R,KGZ,Men,55 - 60kg,M,Bronze
29195,"ALBIEV, Islam-Beka",Beijing,2008,Wrestling,Wrestling Gre-R,RUS,Men,55 - 60kg,M,Gold
29196,"RAHIMOV, Vitaliy",Beijing,2008,Wrestling,Wrestling Gre-R,AZE,Men,55 - 60kg,M,Silver
29197,"SIAMIONAU, Mikhail",Beijing,2008,Wrestling,Wrestling Gre-R,BLR,Men,60 - 66kg,M,Bronze
29198,"VARDANYAN, Armen",Beijing,2008,Wrestling,Wrestling Gre-R,UKR,Men,60 - 66kg,M,Bronze
29199,"GUENOT, Steeve",Beijing,2008,Wrestling,Wrestling Gre-R,FRA,Men,60 - 66kg,M,Gold
29200,"BEGALIEV, Kanatbek",Beijing,2008,Wrestling,Wrestling Gre-R,KGZ,Men,60 - 66kg,M,Silver
29201,"GUENOT, Christophe",Beijing,2008,Wrestling,Wrestling Gre-R,FRA,Men,66 - 74kg,M,Bronze
29202,"YANAKIEV, Yavor",Beijing,2008,Wrestling,Wrestling Gre-R,BUL,Men,66 - 74kg,M,Bronze
29203,"KVIRKELIA, Manuchar",Beijing,2008,Wrestling,Wrestling Gre-R,GEO,Men,66 - 74kg,M,Gold
29204,"CHANG, Yongxiang",Beijing,2008,Wrestling,Wrestling Gre-R,CHN,Men,66 - 74kg,M,Silver
29205,"AVLUCA, Nazmi",Beijing,2008,Wrestling,Wrestling Gre-R,TUR,Men,74 - 84kg,M,Bronze
29206,"MINGUZZI, Andrea",Beijing,2008,Wrestling,Wrestling Gre-R,ITA,Men,74 - 84kg,M,Gold
29207,"FODOR, Zoltan",Beijing,2008,Wrestling,Wrestling Gre-R,HUN,Men,74 - 84kg,M,Silver
29208,"MAMBETOV, Asset",Beijing,2008,Wrestling,Wrestling Gre-R,KAZ,Men,84 - 96kg,M,Bronze
29209,"WHEELER, Adam",Beijing,2008,Wrestling,Wrestling Gre-R,USA,Men,84 - 96kg,M,Bronze
29210,"KHUSHTOV, Aslanbek",Beijing,2008,Wrestling,Wrestling Gre-R,RUS,Men,84 - 96kg,M,Gold
29211,"ENGLICH, Mirko",Beijing,2008,Wrestling,Wrestling Gre-R,GER,Men,84 - 96kg,M,Silver
29212,"MIZGAITIS, Mindaugas",Beijing,2008,Wrestling,Wrestling Gre-R,LTU,Men,96 - 120kg,M,Bronze
29213,"PATRIKEEV, Yuri",Beijing,2008,Wrestling,Wrestling Gre-R,ARM,Men,96 - 120kg,M,Bronze
29214,"LOPEZ, Mijain",Beijing,2008,Wrestling,Wrestling Gre-R,CUB,Men,96 - 120kg,M,Gold
29215,"BAROEV, Khasan",Beijing,2008,Wrestling,Wrestling Gre-R,RUS,Men,96 - 120kg,M,Silver

sort_index

In [29]:
oo.head()

,Athlete,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
0,"HAJOS, Alfred",Athens,1896,Aquatics,Swimming,HUN,Men,100m freestyle,M,Gold
1,"HERSCHMANN, Otto",Athens,1896,Aquatics,Swimming,AUT,Men,100m freestyle,M,Silver
2,"DRIVAS, Dimitrios",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Bronze
3,"MALOKINIS, Ioannis",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Gold
4,"CHASAPIS, Spiridon",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Silver

In [38]:
oo.set_index('Athlete',inplace=True)
oo.head()

,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
Athlete,,,,,,,,,
"HAJOS, Alfred",Athens,1896,Aquatics,Swimming,HUN,Men,100m freestyle,M,Gold
"HERSCHMANN, Otto",Athens,1896,Aquatics,Swimming,AUT,Men,100m freestyle,M,Silver
"DRIVAS, Dimitrios",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Bronze
"MALOKINIS, Ioannis",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Gold
"CHASAPIS, Spiridon",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Silver

Sort_index()

In [44]:
oo.sort_index(inplace=True)
oo.head()

,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
Athlete,,,,,,,,,
"AABYE, Edgar",Paris,1900,Tug of War,Tug of War,ZZX,Men,tug of war,M,Gold
"AALTONEN, Arvo Ossian",Antwerp,1920,Aquatics,Swimming,FIN,Men,200m breaststroke,M,Bronze
"AALTONEN, Arvo Ossian",Antwerp,1920,Aquatics,Swimming,FIN,Men,400m breaststroke,M,Bronze
"AALTONEN, Paavo Johannes",London,1948,Gymnastics,Artistic G.,FIN,Men,pommel horse,M,Gold
"AALTONEN, Paavo Johannes",London,1948,Gymnastics,Artistic G.,FIN,Men,team competition,M,Gold

In [45]:
oo.sort_index(inplace=True,ascending=False)
oo.head()

,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
Athlete,,,,,,,,,
"ÖSTRAND, Per-Olof",Helsinki,1952,Aquatics,Swimming,SWE,Men,400m freestyle,M,Bronze
"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"army rifle, 300m, 3 positions",M,Bronze
"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"free rifle, team",M,Silver
"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"army rifle, 300m, standing",M,Silver
"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"army rifle, 300m, prone",M,Bronze

loc and iloc

In [47]:
oo.reset_index(inplace=True)

In [48]:
oo.head()

,Athlete,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
0,"ÖSTRAND, Per-Olof",Helsinki,1952,Aquatics,Swimming,SWE,Men,400m freestyle,M,Bronze
1,"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"army rifle, 300m, 3 positions",M,Bronze
2,"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"free rifle, team",M,Silver
3,"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"army rifle, 300m, standing",M,Silver
4,"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"army rifle, 300m, prone",M,Bronze

In [53]:
oo.iloc[1]

Athlete                            ÖSTMO, Ole
City                                    Paris
Edition                                  1900
Sport                                Shooting
Discipline                           Shooting
NOC                                       NOR
Gender                                    Men
Event           army rifle, 300m, 3 positions
Event_gender                                M
Medal                                  Bronze
Name: 1, dtype: object

In [57]:
oo.iloc[[203,22,190]]

,Athlete,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
203,"ZHOU, Luxin",Beijing,2008,Aquatics,Diving,CHN,Men,10m platform,M,Silver
22,"ZÜHLKE, Steffen",Seoul,1988,Rowing,Rowing,GDR,Men,quadruple sculls without coxswain (4x),M,Bronze
190,"ZHOVNIR, Olha",Beijing,2008,Fencing,Fencing,UKR,Women,sabre team,W,Gold

In [59]:
oo.iloc[2:6]

,Athlete,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
2,"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"free rifle, team",M,Silver
3,"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"army rifle, 300m, standing",M,Silver
4,"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"army rifle, 300m, prone",M,Bronze
5,"ÖSTERVOLD, Ole Olsen",Antwerp,1920,Sailing,Sailing,NOR,Men,12m (rating 1907),X,Gold

In [66]:
oo.set_index('Athlete',inplace=True)

In [67]:
oo.head()

,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
Athlete,,,,,,,,,
"ÖSTRAND, Per-Olof",Helsinki,1952,Aquatics,Swimming,SWE,Men,400m freestyle,M,Bronze
"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"army rifle, 300m, 3 positions",M,Bronze
"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"free rifle, team",M,Silver
"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"army rifle, 300m, standing",M,Silver
"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"army rifle, 300m, prone",M,Bronze

In [69]:
oo.head()

,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
Athlete,,,,,,,,,
"ÖSTRAND, Per-Olof",Helsinki,1952,Aquatics,Swimming,SWE,Men,400m freestyle,M,Bronze
"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"army rifle, 300m, 3 positions",M,Bronze
"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"free rifle, team",M,Silver
"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"army rifle, 300m, standing",M,Silver
"ÖSTMO, Ole",Paris,1900,Shooting,Shooting,NOR,Men,"army rifle, 300m, prone",M,Bronze

In [71]:
oo.loc['BOLT, Usain']

,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
Athlete,,,,,,,,,
"BOLT, Usain",Beijing,2008,Athletics,Athletics,JAM,Men,100m,M,Gold
"BOLT, Usain",Beijing,2008,Athletics,Athletics,JAM,Men,4x100m relay,M,Gold
"BOLT, Usain",Beijing,2008,Athletics,Athletics,JAM,Men,200m,M,Gold